name: SAST

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Start PostgreSQL Container
        run: |
          docker run --name mypostgres -d -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=mydatabase -p 5432:5432 postgres:latest

      - name: Wait for PostgreSQL
        run: |
          until docker exec mypostgres pg_isready -U user; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Build Flask Docker Image
        run: |
          docker build -t myflaskapp .

      - name: Start Flask App Container
        run: |
          docker run --name myflaskapp -d -e DATABASE_URL=postgresql://user:password@localhost/mydatabase -p 5000:5000 myflaskapp

      - name: Wait for Flask app
        run: |
          until curl -s http://localhost:5000; do
            echo "Waiting for Flask app..."
            sleep 5
          done

      - name: Run database migrations
        run: |
          docker exec myflaskapp flask db migrate
          docker exec myflaskapp flask db upgrade

      - name: Run ZAP scan
        run: |
          docker run -t owasp/zap2docker-stable zap-baseline.py -t http://localhost:5000 -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v2
        with:
          name: zap-report
          path: zap_report.html

