name: DAST

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow against'
        required: true
        default: 'main'
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create docker network
        run: |
          docker network create mynetwork

      - name: Start PostgreSQL Container
        run: |
          docker run --network=mynetwork --name mypostgres -d -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=mydatabase -p 5432:5432 postgres:latest

      - name: Wait for PostgreSQL
        run: |
          until docker exec mypostgres pg_isready -U user; do
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Build Flask Docker Image
        run: |
          docker build -t myflaskapp .

      - name: Start Flask App Container
        run: |
          docker run --network=mynetwork --name myflaskapp -d -e DATABASE_URL=postgresql://user:password@mypostgres/mydatabase -p 5000:5000 myflaskapp

      - name: Wait for Flask app
        run: |
          until curl -s http://localhost:5000; do
            echo "Waiting for Flask app..."
            sleep 5
          done

      - name: Run database migrations
        run: |
          docker exec myflaskapp flask db upgrade
          docker exec myflaskapp flask db migrate

      # - name: Run ZAP scan
      #   run: |
      #     docker run --network=mynetwork -t owasp/zap2docker-stable zap-baseline.py -t http://myflaskapp:5000 -r zap_report.html

      # - name: ZAP Scan
      #   uses: zaproxy/action-baseline@v0.15.0
      #     with:
      #       token: ${{ secrets.GITHUB_TOKEN }}
      #       docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
      #       target: 'https://www.zaproxy.org'
      #       rules_file_name: '.zap/rules.tsv'
      #       cmd_options: '-a'

      - name: Start ZAP Container
        run: |
          docker run --network=mynetwork --name zaproxy -d -p 8080:8080 -v ${{ github.workspace }}/zapreports:/zap/reports zaproxy/zap-stable zap.sh -daemon -port 8080

      - name: Wait for ZAP to start
        run: |
          sleep 5

      - name: ZAP Scan
        run: |
          docker exec zaproxy zap-baseline.py -t http://myflaskapp:5000 -r /zap/reports/zap_report.html
          # docker run -t -v zapreports:/zap/reports owasp/zap2docker-stable zap-baseline.py -t http://your-application-url.com -r /zap/reports/zap_report.htm    l


      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zapreports/zap_report.html

