name: CI/CD to Azure Container Apps via ACR

on:
  push:
    branches: [ "aliaksei", "main", "vitalii"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: ${{ secrets.AZURE_ACR_NAME }}
      APP_NAME: ${{ secrets.AZURE_CONTAINERAPP_NAME }}
      RG_NAME:  ${{ secrets.AZURE_RG }}
      SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DATABASE_URL: "sqlite:///memory"

    steps:
      - name: Checkout
        uses: actions/checkout@v4


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
#        JESLI UNITTESTY ZADZIA≈ÅAJA
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
         pytest --maxfail=1 --disable-warnings -q



      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to ACR
        run: az acr login --name $ACR_NAME

      - name: Build and push image to ACR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.ACR_NAME }}.azurecr.io/diplomacy-backend:latest
            ${{ env.ACR_NAME }}.azurecr.io/diplomacy-backend:${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/cli@v2
        with:
          inlineScript: |
            az account set --subscription $SUBSCRIPTION_ID

            # az containerapp update \
            #   --name $APP_NAME \
            #   --resource-group $RG_NAME \
            #   --image $ACR_NAME.azurecr.io/diplomacy-backend:${{ github.sha }} \
            #   --set-env-vars DATABASE_URL='${{ secrets.DATABASE_URL }}' FLASK_ENV='production'

            az aks get-credentials --resource-group diplomacy_cluster_france --name diplomacy_cluster 

            kubectl set image deployment/diplomacy-app-deployment diplomacy-app-container=diplomacycontainers.azurecr.io/diplomacy/diplomacy-app:${{ github.sha }}



